sensor_kit_base_link:
  camera0/camera_link:
    x: 0.10731
    y: 0.56343
    z: -0.27697
    roll: -0.025
    pitch: 0.315
    yaw: 1.035
  camera1/camera_link:
    x: -0.10731
    y: -0.56343
    z: -0.27697
    roll: -0.025
    pitch: 0.32
    yaw: -2.12
  camera2/camera_link:
    x: 0.10731
    y: -0.56343
    z: -0.27697
    roll: -0.00
    pitch: 0.335
    yaw: -1.04
  velodyne_top_base_link:
    x: -0.478
    y: 0.0125
    z: 1.952
    roll: 0.0
    pitch: 0.0
    yaw: 3.14159265
  velodyne_left_base_link:
    x: 3.25
    y: 0.55
    z: 0.825
    roll: 0.0
    pitch: 0.0
    yaw: 0.1
  velodyne_right_base_link:
    x: 3.25
    y: -0.55
    z: 0.825
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: 0.5
    y: 0.0
    z: 1.952
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: -0.2
    y: 0.0
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
